package:
    name: tesseract_planning
    version: "0.1.0"

source:
    path: ../../workspace

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - gtest
      - gmock
      - cmake
      - ninja # [win]
      - make # [linux]
      - pkg-config
      - swig
      - colcon-common-extensions 
      - lcov
      - {{ cdt('mesa-libgl-devel') }}    # [linux]
      - {{ cdt('mesa-dri-drivers') }}    # [linux]
    host:
      - boost-cpp 
      - eigen 
      - tinyxml2
      - console_bridge
      - assimp
      - urdfdom
      - fcl
      - octomap 
      - orocos-kdl 
      - pcl
      - gtest
      - gmock
      - pkg-config 
      - xz
      - flann
      - jsoncpp
      - yaml-cpp
      - bullet-cpp
      - liblapack
      - ompl
      - taskflow
      - xorg-libx11    # [unix]
      - xorg-libxext   # [unix]
      - blas
    run:
      - boost-cpp
      - eigen 
      - tinyxml2
      - console_bridge
      - assimp
      - urdfdom
      - fcl
      - octomap 
      - orocos-kdl 
      - pcl
      - gtest
      - gmock
      - xz
      - jsoncpp
      - taskflow 
      - yaml-cpp
      - bullet-cpp
      - liblapack
      - ompl
      - taskflow
      - xorg-libx11    # [unix]
      - xorg-libxext   # [unix]
      - blas

build:
  skip: true # [py<37]
  number: 0

about:
  home: https://github.com/ros-industrial-consortium/tesseract_planning
  summary: Tesseract robotics motion planning framework